# Metadata
name: SITE NAME
description: SITE DESCRIPTION
author: jmegs

# Where things are
# changing this to have a clean site directory
source: ./site
destination: ./dist

# File Handling
exclude: ["node_modules", "gulpfile.babel.js", "package.json", "yarn.lock", ".babelrc", "webpack.config.js", "netlify.toml"]

# Conversion
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "fenced_code_blocks", "footnotes", "highlight"]

# Output
permalink: pretty

# Collections
# Set this to a collection name with 
# a corresponding folder called _COLLECTION_NAME

# collections:
#   projects:
#     output: true
#     permalink: /:collection/:path/

# Custom Configs accessible as site.VARIABLE
# image_url: "/assets/images"